import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { qrSvg } from "@/lib/qr";
import { formatCents } from "@/lib/money";
import { formatEventDate, formatEventTime } from "@/lib/when";
import { Badge } from "@/components/ui";

export const metadata = {
  title: "Your tickets",
  // A ticket link is a bearer token; it has no business in a search index.
  robots: { index: false, follow: false },
};

/**
 * The buyer's own page. No account — the token in the URL is the
 * authorisation, the same bargain the RSVP link makes. Each ticket carries
 * its own code so a group can split up at the door.
 */
export default async function TicketsPage({ params }: PageProps<"/t/[token]">) {
  const { token } = await params;

  const order = await db.order.findUnique({
    where: { token },
    include: {
      event: { select: { id: true, title: true, date: true, city: true, address: true } },
      tickets: {
        orderBy: { createdAt: "asc" },
        include: { ticketTier: { select: { name: true, priceCents: true } } },
      },
    },
  });
  if (!order) notFound();

  const live = order.tickets.filter((t) => !t.voidedAt);
  const codes = await Promise.all(live.map((t) => qrSvg(t.token)));

  return (
    <main className="mx-auto w-full max-w-md flex-1 px-4 py-10">
      <p className="text-center text-[13px] font-medium tracking-wide text-ink-mute uppercase">
        {order.status === "PAID" ? "Ticket" : order.status === "PENDING" ? "Reserved" : "Void"}
      </p>
      <h1 className="font-event mt-2 text-center text-[30px] leading-tight text-ink">
        {order.event.title}
      </h1>
      <p className="mt-2 text-center text-ink-soft">
        {formatEventDate(order.event.date, true) ?? "Date to be announced"}
        {order.event.date ? ` · ${formatEventTime(order.event.date)}` : ""}
      </p>
      <p className="text-center text-ink-soft">{order.event.address || order.event.city}</p>

      {order.status === "PENDING" ? (
        <p className="mt-5 rounded-card border border-line bg-amber-wash px-4 py-3 text-center text-[14px] text-amber">
          Held for you. Settle up with the organiser and this turns into a ticket.
        </p>
      ) : null}
      {order.status === "REFUNDED" || order.status === "CANCELLED" ? (
        <p className="mt-5 rounded-card border border-line bg-danger-wash px-4 py-3 text-center text-[14px] text-danger">
          These tickets were {order.status === "REFUNDED" ? "refunded" : "cancelled"} and won’t scan.
        </p>
      ) : null}

      <div className="mt-8 space-y-4">
        {live.map((ticket, index) => (
          <div key={ticket.id} className="rounded-card border border-line bg-surface p-5 text-center">
            <div className="flex items-center justify-between">
              <span className="text-[13px] font-medium text-ink">{ticket.ticketTier.name}</span>
              {ticket.checkedInAt ? (
                <Badge tone="forest">Used</Badge>
              ) : (
                <Badge>
                  {index + 1} of {live.length}
                </Badge>
              )}
            </div>
            <div
              className="mx-auto mt-4 w-44 [&>svg]:h-auto [&>svg]:w-full"
              // Generated by lib/qr.ts from the ticket token; no user input.
              dangerouslySetInnerHTML={{ __html: codes[index] }}
            />
            <p
              className="mt-3 font-mono text-[12px] tracking-wider text-ink-mute"
              data-testid="ticket-token"
              data-token={ticket.token}
            >
              {ticket.token.slice(0, 8).toUpperCase()}
            </p>
            <p className="mt-1 text-[13px] text-ink-soft">{ticket.holderName ?? order.name}</p>
          </div>
        ))}
      </div>

      <p className="mt-8 text-center text-[13px] text-ink-mute">
        {live.length} {live.length === 1 ? "ticket" : "tickets"} ·{" "}
        {order.totalCents === 0 ? "Free" : formatCents(order.totalCents)} · keep this link
      </p>
    </main>
  );
}
