// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // generate does not need a live URL; migrate/seed do. They must not go
    // through a connection pooler: `migrate deploy` takes a Postgres
    // advisory lock, which a transaction-mode pooler can hand to a different
    // backend on the next statement, and the build then times out waiting
    // for its own lock. Prefer DIRECT_URL, then the non-pooled URL Vercel's
    // Neon integration provides, and only then the pooled DATABASE_URL.
    url:
      process.env.DIRECT_URL ??
      process.env.DATABASE_POSTGRES_URL_NON_POOLING ??
      process.env.DATABASE_URL ??
      "",
  },
});
