// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // generate does not need a live URL; migrate/seed do. Prefer a direct
    // (non-pooled) URL when the host provides one.
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "",
  },
});
